databases:
  - name: codematic
    databaseName: codematicdb
    user: code

services:
  - type: web
    name: codematicapi
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn codematic.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: codematic
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.10.5
  - type: redis
    name: thor-redis
    region: Frankfurt
    plan: starter # we choose a plan with persistence to ensure tasks are not lost upon restart
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: [ ] # only allow internal connections