name: Deploy to Render

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10.5]

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
        CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
        REDIS_URL: ${{ secrets.REDIS_URL }}
        CELERY_RESULT_BACKEND: ${{ secrets.CELERY_RESULT_BACKEND }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
      run: |
        python manage.py test

    - name: Tear Down Redis
      run: docker stop redis

    - name: Install Render CLI
      run: |
        curl -fLo render https://github.com/render-oss/render-cli/releases/download/v0.1.9/render-linux-x86_64
        chmod +x render
        sudo mv render /usr/local/bin/

    - name: Deploy to Render
      env:
        RENDERCLI_APIKEY: ${{ secrets.RENDERCLI_APIKEY }}
      run: |
        render blueprint launch
